var jsonData=[
    {
        "ModelID": 27,
        "FordDivisionId": 114,
        "VehicleName": "Ford TT Delivery Truck",
        "VehicleYear": 1925,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 26,
        "VehicleEngineId": 54,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 65,
        "ModelScaleId": 81,
        "ModelColorId": 92,
        "ModelImagePrefix": "FTT19251",
        "DateCreated": "2008-02-18T18:28:14",
        "CreatedBy": "0",
        "DateModified": "2008-03-05T05:09:56",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Wagon Delivery",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "Matchbox",
        "ModelScaleName": "1:18",
        "ModelColorName": "black/white"
    },
    {
        "ModelID": 85,
        "FordDivisionId": 114,
        "VehicleName": "Ford Model T Fire Track",
        "VehicleYear": 1926,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 47,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 71,
        "ModelScaleId": 87,
        "ModelColorId": 106,
        "ModelImagePrefix": "FTFT1926",
        "DateCreated": "2008-03-13T04:48:39",
        "CreatedBy": "0",
        "DateModified": "2008-03-13T04:48:39",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Other",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Signature",
        "ModelScaleName": "1:32",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 12,
        "FordDivisionId": 114,
        "VehicleName": "Ford Model A Pickup",
        "VehicleYear": 1931,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 71,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "FMA1931",
        "DateCreated": "2008-03-05T04:51:52",
        "CreatedBy": "0",
        "DateModified": "2008-03-05T04:52:15",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Signature",
        "ModelScaleName": "1:18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 90,
        "FordDivisionId": 114,
        "VehicleName": "Ford Model A Sedan",
        "VehicleYear": 1931,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 12,
        "VehicleEngineId": 54,
        "VehicleHighlight": "The Ford Model A of 1927�1931 (also colloquially called the A-Model Ford or the A, and A-bone) was the second huge success for the Ford Motor Company, after its predecessor, the Model T.  First produced on October 20, 1927, but not sold until December 2, it  replaced the venerable Model T, which had been produced for 18 years. This new Model A (a previous model had used the Model A name back in 1903�1904) was designated as a 1927 model and was available in four standard colors, but not black. The Model A was produced through 1931. When production ended in  March,        1932, there were 4,849,340 Model As made in all styles. Its  successor was the Model B, which featured an updated 4-cylinder engine, followed by the Model_18 which introduced Ford new Flathead V8 engine.",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "FMAS1931",
        "DateCreated": "2011-02-21T05: 47: 53",
        "CreatedBy": "0",
        "DateModified": "2011-02-21T06: 18: 09",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Sedan",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 31,
        "FordDivisionId": 114,
        "VehicleName": "Ford Roadster Street Rod",
        "VehicleYear": 1932,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 23,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "FRSR1932",
        "DateCreated": "2008-03-06T05: 20: 59",
        "CreatedBy": "0",
        "DateModified": "2010-12-10T06: 12: 28",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "Roadster",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 55,
        "FordDivisionId": 114,
        "VehicleName": "Ford 34 Coupe",
        "VehicleYear": 1934,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 69,
        "ModelScaleId": 82,
        "ModelColorId": 106,
        "ModelImagePrefix": "FCP1934",
        "DateCreated": "2008-03-09T05: 48: 41",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T05: 48: 41",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Redbox",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 14,
        "FordDivisionId": 114,
        "VehicleName": "Ford Pickup",
        "VehicleYear": 1934,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "FPK1934",
        "DateCreated": "2008-03-05T05: 13: 11",
        "CreatedBy": "0",
        "DateModified": "2008-03-05T05: 21: 51",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 13,
        "FordDivisionId": 114,
        "VehicleName": "Ford Pickup Pro Street",
        "VehicleYear": 1934,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 99,
        "ModelImagePrefix": "FPS1934",
        "DateCreated": "2008-03-05T05: 04: 14",
        "CreatedBy": "0",
        "DateModified": "2008-03-05T05: 04: 14",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Gold"
    },
    {
        "ModelID": 11,
        "FordDivisionId": 114,
        "VehicleName": "Ford Roaster",
        "VehicleYear": 1934,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 73,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "FRS1934",
        "DateCreated": "2008-03-05T05: 47: 38",
        "CreatedBy": "0",
        "DateModified": "2008-03-05T05: 47: 38",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Solido (France)",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 21,
        "FordDivisionId": 114,
        "VehicleName": "Ford Deluxe Cabriolet",
        "VehicleYear": 1936,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 81,
        "ModelColorId": 109,
        "ModelImagePrefix": "FDC1936",
        "DateCreated": "2008-02-08T01: 26: 02",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 30: 05",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 18",
        "ModelColorName": "White"
    },
    {
        "ModelID": 33,
        "FordDivisionId": 114,
        "VehicleName": "Ford Plateau Pneu",
        "VehicleYear": 1936,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 49,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 73,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "FPP1937",
        "DateCreated": "2008-03-06T05: 57: 42",
        "CreatedBy": "0",
        "DateModified": "2008-03-06T05: 57: 42",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "I6",
        "ModelManufacturerName": "Solido (France)",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 32,
        "FordDivisionId": 114,
        "VehicleName": "Ford Convertible",
        "VehicleYear": 1937,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Ford line of cars was updated in 1937 with one major change � the introduction of an entry-level 136 in� (2.2 L) V8 in addition to the popular 221 in� (3.6 L) unit. The model was a refresh of its predecessor, itself based on Ford V8-powered Model 40A and was the company main product. It was redesigned more thoroughly in 1941. The 1937 Ford featured a more rounded look with fine horizontal bars in the convex front and hood-side grilles. The front grille was v-shaped rather than following the fenders into a pentagon shape as on the 1936 model. Faired-in headlights were a major modernization found on both the Standard and DeLuxe trim versions, though much of the rest of the design was shared between Ford two lines. Slantback sedans gained a rear trunk door, though space was limited, and Trunkback versions continued gaining sales.",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "FCT1937",
        "DateCreated": "2008-03-06T05: 36: 39",
        "CreatedBy": "0",
        "DateModified": "2008-03-07T00: 33: 55",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 52,
        "FordDivisionId": 114,
        "VehicleName": "Ford 1940 Coupe",
        "VehicleYear": 1940,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 69,
        "ModelScaleId": 82,
        "ModelColorId": 106,
        "ModelImagePrefix": "FRDC1940",
        "DateCreated": "2008-03-09T01: 17: 31",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T01: 17: 31",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Redbox",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 51,
        "FordDivisionId": 114,
        "VehicleName": "Ford Sedan Delivery",
        "VehicleYear": 1940,
        "VehicleCategoryId": 5,
        "VehicleBodyStyleId": 19,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 94,
        "ModelImagePrefix": "FSD1940",
        "DateCreated": "2008-03-09T01: 03: 03",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T01: 03: 03",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Van",
        "VehicleBodyStyleName": "Delivery Van",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 38,
        "FordDivisionId": 114,
        "VehicleName": "Ford 49 Convertible",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 72,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "FRC1949",
        "DateCreated": "2008-03-07T06: 31: 52",
        "CreatedBy": "0",
        "DateModified": "2008-03-07T06: 31: 52",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Solido",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 41,
        "FordDivisionId": 114,
        "VehicleName": "Ford Coupe",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "FCP1949",
        "DateCreated": "2008-03-02T21: 58: 49",
        "CreatedBy": "0",
        "DateModified": "2008-03-02T21: 58: 49",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 34,
        "FordDivisionId": 114,
        "VehicleName": "Ford Police",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 12,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Ford Police Car 1949 is only police car was powered by a stock 100-horsepower flat-head V-8. The Ford did not have any of the heavy duty items that you would see in police cars today. It did not even have a police radio. If the officers in the Ford needed to get a hold of headquarters, there were dozens of call boxes throughout the city for communication. Certainly a much simpler time than is the case today.",
        "ModelManufacturerId": 72,
        "ModelScaleId": 81,
        "ModelColorId": 92,
        "ModelImagePrefix": "FPC1949",
        "DateCreated": "2008-03-06T06: 12: 08",
        "CreatedBy": "0",
        "DateModified": "2008-03-07T00: 26: 44",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Sedan",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Solido",
        "ModelScaleName": "1: 18",
        "ModelColorName": "black/white"
    },
    {
        "ModelID": 3,
        "FordDivisionId": 114,
        "VehicleName": "Ford Woody Wagon",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 13,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "FWW1949",
        "DateCreated": "2008-02-07T17: 20: 51",
        "CreatedBy": "0",
        "DateModified": "2011-05-11T21: 34: 41",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Station Wagon",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 48,
        "FordDivisionId": 114,
        "VehicleName": "Ford 50 Convertible",
        "VehicleYear": 1950,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "FCT1950",
        "DateCreated": "2008-03-08T05: 49: 36",
        "CreatedBy": "0",
        "DateModified": "2008-03-08T05: 49: 36",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 88,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-1 Pick Up",
        "VehicleYear": 1951,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "F11951",
        "DateCreated": "2008-03-11T03: 35: 49",
        "CreatedBy": "0",
        "DateModified": "2008-03-11T03: 35: 49",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 37,
        "FordDivisionId": 114,
        "VehicleName": "Ford Stake Truck",
        "VehicleYear": 1951,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 60,
        "ModelScaleId": 83,
        "ModelColorId": 94,
        "ModelImagePrefix": "FST1951",
        "DateCreated": "2008-03-07T05: 35: 28",
        "CreatedBy": "0",
        "DateModified": "2008-03-07T05: 35: 28",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Golden Wheel",
        "ModelScaleName": "1: 25",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 22,
        "FordDivisionId": 114,
        "VehicleName": "F-100 Panel Van",
        "VehicleYear": 1953,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 25,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "FPV1953",
        "DateCreated": "2008-02-08T01: 27: 21",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 24: 11",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Van",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 74,
        "FordDivisionId": 114,
        "VehicleName": "Ford Crestline Sunliner",
        "VehicleYear": 1953,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 96,
        "ModelImagePrefix": "FCREST1953",
        "DateCreated": "2008-03-12T05: 14: 51",
        "CreatedBy": "0",
        "DateModified": "2008-03-12T05: 14: 51",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Dark Blue"
    },
    {
        "ModelID": 43,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-100 Pick Up",
        "VehicleYear": 1953,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 77,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "F100T1953",
        "DateCreated": "2008-03-03T05: 27: 11",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T05: 27: 11",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Yan Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 19,
        "FordDivisionId": 114,
        "VehicleName": "Ford Thunderbird (1955)",
        "VehicleYear": 1955,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 11,
        "VehicleEngineId": 49,
        "VehicleHighlight": "The 1955 Thunderbird was the first of a legendary line of Fords and was designed to compete Chevrolet Corvette. The Thunderbird was always more of a personal car than an outright sports car.",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 81,
        "ModelColorId": 105,
        "ModelImagePrefix": "FTH1955",
        "DateCreated": "2008-02-08T01: 22: 32",
        "CreatedBy": "0",
        "DateModified": "2010-04-04T20: 52: 18",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop Convertible",
        "VehicleEngineName": "I6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Pink"
    },
    {
        "ModelID": 60,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-100 (1956)",
        "VehicleYear": 1956,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 75,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "F1001956",
        "DateCreated": "2008-03-09T18: 13: 37",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T18: 13: 37",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "TootsieToy",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 73,
        "FordDivisionId": 114,
        "VehicleName": "Ford F100 Tow Truck",
        "VehicleYear": 1956,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "F100Tow56",
        "DateCreated": "2008-03-11T03: 06: 04",
        "CreatedBy": "0",
        "DateModified": "2008-03-11T03: 06: 04",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 23,
        "FordDivisionId": 114,
        "VehicleName": "Ford Fairlane Skyliner",
        "VehicleYear": 1957,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 11,
        "VehicleEngineId": 49,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 74,
        "ModelScaleId": 81,
        "ModelColorId": 98,
        "ModelImagePrefix": "FFS1957",
        "DateCreated": "2008-02-08T01: 28: 38",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T16: 10: 11",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop Convertible",
        "VehicleEngineName": "I6",
        "ModelManufacturerName": "Sun Star",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Ford"
    },
    {
        "ModelID": 57,
        "FordDivisionId": 114,
        "VehicleName": "Ford Panel Delivery",
        "VehicleYear": 1957,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 13,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 63,
        "ModelScaleId": 82,
        "ModelColorId": 111,
        "ModelImagePrefix": "FPD1957",
        "DateCreated": "2008-03-09T06: 57: 38",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T06: 57: 38",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Station Wagon",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Jonny Lighting",
        "ModelScaleName": "1: 24",
        "ModelColorName": "White/Yellow/Red"
    },
    {
        "ModelID": 40,
        "FordDivisionId": 114,
        "VehicleName": "Ford Ranchero",
        "VehicleYear": 1957,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 49,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 79,
        "ModelScaleId": 81,
        "ModelColorId": 107,
        "ModelImagePrefix": "FRC1957",
        "DateCreated": "2008-03-03T04: 40: 20",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T04: 40: 20",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "I6",
        "ModelManufacturerName": "Yat Ming U.S.A Inc.",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red/White"
    },
    {
        "ModelID": 89,
        "FordDivisionId": 114,
        "VehicleName": "Edsel Citation",
        "VehicleYear": 1958,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "Back in 1956, Ford Motor Company realized that there was a void in their selections of mid-size automobiles.  While Chevrolet owners could 'move up' to a Buick, Pontiac or Oldsmobile (and Dodge owners could advance to a Plymouth or Chrysler), Ford buyers were looking at Mercury alone.  The perception was that Ford was losing customers to other manufacturers when the time came to trade-up. rnrnIn order to correct the problem, Ford instituted plans for an entirely new car division, and an entirely new car.  The design of the car was to be completely unique - distinguishable from any angle.  And the promotional build-up of the car would be like nothing else. The 1958 Edsel came in two sizes - big and bigger!  The Senior Series cars are Citation and Corsair models.  They were built on the large Mercury-based frame.  The Junior series cars are Rangers, Pacers and station wagons Bermuda, Villager and Roundup, which were built on the smaller Ford-based frame. One of the most talked about feature was the teletouch shifter, which controlled the automatic transmission selection electronically from push buttons in the center of the steering wheel hub.  (A series of planetary gears in the column keeps the buttons stationary as the wheel turns.)  Many other Edsel-original ideas are still found on today cars. The car was referred to as the Experimental from its inception.  The name Edsel was bestowed by Special Products Division General Manager Richard Krafve, after reviewing a list of nearly 8,     000 suggestions from their advertising firm, Ford employees and renowned poet Marianne Moore who was solicited for ideas.  After a massive promotional campaign, which included multi-page ads in major national magazines, some 2.5 million Americans poured into Edsel dealerships on E-Day, September 4, 1957.  But it was quickly apparent that few cars were actually being sold.  The public expectation was much higher than the car could live up to, and sales reflected the disappointment. There was a combination of other factors that led to the name Edsel becoming synonymous with failure - By the time the first Edsel hit the showroom, the country was in a recession.  (For comparison, 1958 DeSoto sales were down 54% from 1957. Buick was down 33%, Mercury 48%, Oldsmobile 18%, Dodge 47%, Pontiac 28%..  probably the worst year since World War II to unveil a new car line!)  Car-buying habits had turned toward smaller and more fuel efficient cars.  Edsel styling was radical, and not to everyone liking.  On the assembly line, Edsel was run between Fords or Mercury, causing the assembler to have to interrupt his routine and sometimes forget to install some parts.  The Edsel also suffered from parts that would not fit together correctly.   Because of problems with suppliers, many of the early cars arrived at the dealerships with parts missing.  Many dealers were poorly equipped to replace the parts or add on accessories.  Ford Vice President Robert McNamara offered little support to the Edsel Division.  The Edsel was more expensive than other comparable cars, and the price of the loaded, top-of-the-line models that were first on the showroom floor scared many buyers.  There was no owner loyalty to count on.  And, finally, it had a funny name. The Edsel Division was in a death spiral.  The more cars that failed to sell, the more dealers dropped their Edsel franchise.  The more dealers that folded, the more the public was afraid to buy the car. After three model years and just 110,      847 Edsels later, Ford Motor Company threw in the towel, and went about trying to forget about the whole ordeal.",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 103,
        "ModelImagePrefix": "EDS1958",
        "DateCreated": "2008-03-11T03: 52: 35",
        "CreatedBy": "0",
        "DateModified": "2008-03-11T21: 15: 53",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Light Green"
    },
    {
        "ModelID": 72,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-250",
        "VehicleYear": 1959,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 103,
        "ModelImagePrefix": "F2501959",
        "DateCreated": "2008-03-11T02: 54: 42",
        "CreatedBy": "0",
        "DateModified": "2010-04-23T21: 44: 57",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Light Green"
    },
    {
        "ModelID": 18,
        "FordDivisionId": 114,
        "VehicleName": "Ford Thunderbird (1962)",
        "VehicleYear": 1962,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 50,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 55,
        "ModelScaleId": 81,
        "ModelColorId": 98,
        "ModelImagePrefix": "FTH1962",
        "DateCreated": "2008-02-08T01: 21: 12",
        "CreatedBy": "0",
        "DateModified": "2010-04-04T20: 34: 19",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "I8",
        "ModelManufacturerName": "Anson Classic",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Ford"
    },
    {
        "ModelID": 83,
        "FordDivisionId": 114,
        "VehicleName": "Ford Falcon",
        "VehicleYear": 1963,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 12,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Ford Falcon was an automobile produced by Ford Motor Company from 1960 through 1970. It was manufactured in the USA, Canada, Australia, Argentina, Mexico and Chile. It was a huge sales success for Ford initially, handily outselling rival compacts from Chrysler and General Motors introduced at the same time. During its lifespan, the Falcon was offered in a wide range of body styles: two-door and four-door sedans, two and four door station wagons, two door hardtops, convertibles, and a sedan delivery and the Ranchero pickup.",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 95,
        "ModelImagePrefix": "FLCN1963",
        "DateCreated": "2008-03-12T05: 01: 31",
        "CreatedBy": "0",
        "DateModified": "2008-03-14T01: 46: 16",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Sedan",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Braun"
    },
    {
        "ModelID": 17,
        "FordDivisionId": 114,
        "VehicleName": "Ford Thunderbird",
        "VehicleYear": 1963,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 10,
        "VehicleEngineId": 50,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "FTH1963",
        "DateCreated": "2008-02-08T01: 19: 55",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 34: 11",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop",
        "VehicleEngineName": "I8",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 54,
        "FordDivisionId": 114,
        "VehicleName": "Ford Fairlane Thunderbolt",
        "VehicleYear": 1964,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 12,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 95,
        "ModelImagePrefix": "FFT1964",
        "DateCreated": "2008-03-09T05: 38: 44",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T05: 42: 39",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Sedan",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Braun"
    },
    {
        "ModelID": 45,
        "FordDivisionId": 114,
        "VehicleName": "Ford Galaxie 500",
        "VehicleYear": 1964,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 74,
        "ModelScaleId": 81,
        "ModelColorId": 110,
        "ModelImagePrefix": "FG5001964",
        "DateCreated": "2008-03-03T05:45:52",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T05:45:52",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Sun Star",
        "ModelScaleName": "1:18",
        "ModelColorName": "White/Red"
    },
    {
        "ModelID": 44,
        "FordDivisionId": 114,
        "VehicleName": "Ford F100 PickUp",
        "VehicleYear": 1965,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 74,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "F1001965",
        "DateCreated": "2008-03-03T05:18:48",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T05:24:11",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Sun Star",
        "ModelScaleName": "1:18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 67,
        "FordDivisionId": 114,
        "VehicleName": "Ford Torino Talladega",
        "VehicleYear": 1969,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 96,
        "ModelImagePrefix": "FTT1969",
        "DateCreated": "2008-03-09T22:57:09",
        "CreatedBy": "0",
        "DateModified": "2010-11-30T18:25:08",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1:18",
        "ModelColorName": "Dark Blue"
    },
    {
        "ModelID": 63,
        "FordDivisionId": 114,
        "VehicleName": "Ford Torino Cobra",
        "VehicleYear": 1971,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 59,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "FTCBR1971",
        "DateCreated": "2008-03-09T21:33:06",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T21: 33: 06",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "ErtlCollectible",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 42,
        "FordDivisionId": 114,
        "VehicleName": "Ford Maverick",
        "VehicleYear": 1974,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 106,
        "ModelImagePrefix": "FMV1974",
        "DateCreated": "2008-03-03T00: 34: 51",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T00: 34: 51",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 29,
        "FordDivisionId": 114,
        "VehicleName": "Ford Maverick Stallion",
        "VehicleYear": 1974,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 54,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 91,
        "ModelImagePrefix": "FMVS1974",
        "DateCreated": "2008-02-18T18: 54: 56",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T18: 55: 48",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black/Silver"
    },
    {
        "ModelID": 66,
        "FordDivisionId": 114,
        "VehicleName": "Ford GT90",
        "VehicleYear": 1990,
        "VehicleCategoryId": 2,
        "VehicleBodyStyleId": 24,
        "VehicleEngineId": 51,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 109,
        "ModelImagePrefix": "FGT90",
        "DateCreated": "2008-03-09T22: 06: 53",
        "CreatedBy": "0",
        "DateModified": "2010-11-30T18: 26: 40",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Sports",
        "VehicleBodyStyleName": "Sports Car",
        "VehicleEngineName": "V10",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "White"
    },
    {
        "ModelID": 49,
        "FordDivisionId": 114,
        "VehicleName": "Ford Explorer Sport",
        "VehicleYear": 1995,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 15,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 69,
        "ModelScaleId": 82,
        "ModelColorId": 100,
        "ModelImagePrefix": "FEX2SPORT",
        "DateCreated": "2008-03-09T00: 29: 54",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T00: 29: 54",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "3-Door Sport Utility",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Redbox",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 50,
        "FordDivisionId": 114,
        "VehicleName": "Ford Explorer Sport Trac",
        "VehicleYear": 1995,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 21,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 83,
        "ModelColorId": 109,
        "ModelImagePrefix": "FEXSTRAC",
        "DateCreated": "2008-03-09T00: 40: 01",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T00: 40: 31",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (4-Door)",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 25",
        "ModelColorName": "White"
    },
    {
        "ModelID": 79,
        "FordDivisionId": 114,
        "VehicleName": "Ford Ranger Splash",
        "VehicleYear": 1995,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 75,
        "ModelScaleId": 82,
        "ModelColorId": 94,
        "ModelImagePrefix": "FRS1995",
        "DateCreated": "2008-03-09T18: 06: 01",
        "CreatedBy": "0",
        "DateModified": "2012-06-03T00: 21: 14",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "TootsieToy",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 7,
        "FordDivisionId": 114,
        "VehicleName": "F-150",
        "VehicleYear": 1997,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 84,
        "ModelColorId": 106,
        "ModelImagePrefix": "F1501997",
        "DateCreated": "2008-02-08T01: 04: 32",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 30: 37",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 26",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 82,
        "FordDivisionId": 114,
        "VehicleName": "Ford 150 XLT",
        "VehicleYear": 1998,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 58,
        "ModelScaleId": 81,
        "ModelColorId": 109,
        "ModelImagePrefix": "F150XLT98",
        "DateCreated": "2008-03-09T23: 05: 41",
        "CreatedBy": "0",
        "DateModified": "2010-05-06T14: 39: 44",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Ertl Collectibles",
        "ModelScaleName": "1: 18",
        "ModelColorName": "White"
    },
    {
        "ModelID": 58,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-350 Super Duty",
        "VehicleYear": 1999,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 85,
        "ModelColorId": 100,
        "ModelImagePrefix": "F3501999",
        "DateCreated": "2008-03-09T16: 59: 48",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T16: 59: 48",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 27",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 86,
        "FordDivisionId": 114,
        "VehicleName": "Ford Focus",
        "VehicleYear": 2000,
        "VehicleCategoryId": 2,
        "VehicleBodyStyleId": 22,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 61,
        "ModelScaleId": 81,
        "ModelColorId": 109,
        "ModelImagePrefix": "FOC2000",
        "DateCreated": "2008-03-13T05: 04: 22",
        "CreatedBy": "0",
        "DateModified": "2008-03-14T01: 23: 46",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Sports",
        "VehicleBodyStyleName": "Race Car",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Hot Wheels",
        "ModelScaleName": "1: 18",
        "ModelColorName": "White"
    },
    {
        "ModelID": 16,
        "FordDivisionId": 114,
        "VehicleName": "Ford 650 Super Crew",
        "VehicleYear": 2002,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 21,
        "VehicleEngineId": 51,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Ford F-650 is a commercial truck offered by Ford. The F-650 Super Duty offers a myriad of customization opportunities. The vehicles have three different diesel engines available with a wide variety of horsepower choices. Buyers have a choice of six manual and five automatic transmissions. rnThe inside of the Ford F650 Crew Cab is by far one of the most comfortable interiors around. Start out with air conditioning, then add a suede headliner. Next throw in a leather seating for 5 and an entertainment package that includes 3 LCD screens, DVD/CD player and premium sound and you got an interior a movie theater would be jealous of. All of this is made possible thanks to the room available inside the Ford F650 Crew cab.",
        "ModelManufacturerId": 68,
        "ModelScaleId": 81,
        "ModelColorId": 98,
        "ModelImagePrefix": "F6502002",
        "DateCreated": "2008-02-08T01: 10: 20",
        "CreatedBy": "0",
        "DateModified": "2019-03-02T00: 35: 51",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (4-Door)",
        "VehicleEngineName": "V10",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Ford"
    },
    {
        "ModelID": 75,
        "FordDivisionId": 114,
        "VehicleName": "Ford Focus SVT",
        "VehicleYear": 2002,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 14,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "In late 2001, Ford in-house performance group, known as Special Vehicle Team (SVT), introduced the SVT Focus to the United States and Canadian markets for the 2002 model year. Ford billed the SVT Focus as the sportiest offering of the Focus to date. Cosmetically, the exterior included unique front and rear bumpers, side skirts, fog lamps, rear spoiler, special exhaust tip and 17inch alloy wheels wearing fairly sticky Y rated 215/45R17 tires from Continental. Mechanically, the car featured a thoroughly reworked version of the 2.0 liter Zetec engine available in other Focus models. Developed by Cosworth, this engine featured many advanced technologies. Included were a special aluminum cylinder head with enlarged intake ports, heavy duty pistons and connecting rods, piston oil squirters, variable camshaft timing, dual stage intake manifold, and a 4-2-1 tubular exhaust header. These additions coupled with an increased 10.2.1 compression ratio bumped horsepower from 130 to 170, while still achieving good fuel economy and emissions. For the transmission, Ford went to German manufacturer GETRAG to provide a six-speed manual which is shared in the Mini Cooper S. This transmission was a twin layshaft design, and included a dual mass flywheel to eliminate vibration. Other changes to complete the package included sharper steering through an increased boost ratio in the steering rack, larger disc brakes on all four corners and stiffened suspension with larger anti-roll bars. Inside the car was offered with several leather bits including seats, and steering wheel. Both the shifter knob and e-brake handle as well as their corresponding boots are in black leather also. Several options were offered including a powered glass sunroof,        8 speaker Audiophile sound system with subwoofer, a cold weather package including heated seats, traction control, a 115V block heater, and heated side mirrors",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 94,
        "ModelImagePrefix": "FFSVT2002",
        "DateCreated": "2008-03-09T18:32:45",
        "CreatedBy": "0",
        "DateModified": "2008-03-14T01:36:41",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "3-Door Hatchback Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1:24",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 9,
        "FordDivisionId": 114,
        "VehicleName": "Ford Focus ZX3",
        "VehicleYear": 2002,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 14,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Focus was introduced in North America in 1999 as a 2000 model, initially as a 3 door hatchback (ZX3), 4 door sedan (ZX4) and 5 door wagon (ZXW).",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 98,
        "ModelImagePrefix": "ZX32002",
        "DateCreated": "2008-02-08T01: 06: 45",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 23: 49",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "3-Door Hatchback Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Ford"
    },
    {
        "ModelID": 56,
        "FordDivisionId": 114,
        "VehicleName": "Ford Focus ZX3 (Tuner)",
        "VehicleYear": 2002,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 14,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 108,
        "ModelImagePrefix": "ZX32002T",
        "DateCreated": "2008-03-09T06: 51: 00",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T06: 51: 00",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "3-Door Hatchback Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Silver"
    },
    {
        "ModelID": 8,
        "FordDivisionId": 114,
        "VehicleName": "Ford Thunderbird",
        "VehicleYear": 2002,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 83,
        "ModelColorId": 103,
        "ModelImagePrefix": "FTH2002",
        "DateCreated": "2008-02-08T01: 05: 35",
        "CreatedBy": "0",
        "DateModified": "2019-03-02T00: 35: 55",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 25",
        "ModelColorName": "Light Green"
    },
    {
        "ModelID": 53,
        "FordDivisionId": 114,
        "VehicleName": "Ford Thunderbird Convertible",
        "VehicleYear": 2002,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 83,
        "ModelColorId": 89,
        "ModelImagePrefix": "FTC2002",
        "DateCreated": "2008-03-09T05: 33: 44",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T05: 33: 44",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 25",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 87,
        "FordDivisionId": 114,
        "VehicleName": "Ford GT",
        "VehicleYear": 2003,
        "VehicleCategoryId": 2,
        "VehicleBodyStyleId": 24,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Ford GT is a mid-engined sports car built by Ford Motor Company from 2003 to 2006. It began as a concept car designed in anticipation of Ford's centennial year and as part of its drive to showcase and revive its heritage names such as Mustang and Thunderbird. Camilo Pardo, the head of Ford's Living Legends studio, is credited as the chief designer of the GT and worked under the guidance of J Mays. The designers drew inspiration from Ford's classic GT40 race cars of the 1960s and the GT is sometimes mistaken for its 1960s counterpart. Positive response on the auto show circuit in 2002 helped persuade the company to produce the car in limited quantities, and the first production versions appeared in 2003. It is a very high-performance, two-seater vehicle with a strong styling resemblance to its racing ancestor and performance to match. The powerplant is a mid-mounted supercharged 5.4 liter V8, producing 550 horsepower (410 kW) and 500 foot-pounds force (680 N�m) of torque. Top speed is 205 mph (330 km/h).",
        "ModelManufacturerId": 57,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "FGTCONC",
        "DateCreated": "2008-03-11T03: 26: 46",
        "CreatedBy": "0",
        "DateModified": "2009-06-28T04: 02: 38",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Sports",
        "VehicleBodyStyleName": "Sports Car",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Beanstalk",
        "ModelScaleName": "1:18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 76,
        "FordDivisionId": 114,
        "VehicleName": "Ford Street KA",
        "VehicleYear": 2003,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 56,
        "ModelScaleId": 82,
        "ModelColorId": 97,
        "ModelImagePrefix": "FKA2003",
        "DateCreated": "2008-03-09T17:25:49",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T17:25:49",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Bburago",
        "ModelScaleName": "1:24",
        "ModelColorName": "Dark Green"
    },
    {
        "ModelID": 5,
        "FordDivisionId": 114,
        "VehicleName": "F150 FX4",
        "VehicleYear": 2004,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 20,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 86,
        "ModelColorId": 89,
        "ModelImagePrefix": "F1502004",
        "DateCreated": "2008-02-07T22:24:13",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15:32:28",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (2-Door)",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1:31",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 78,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-150 4x4",
        "VehicleYear": 2004,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 21,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "F15004",
        "DateCreated": "2008-03-09T19:25:29",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T19:28:17",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (4-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1:18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 4,
        "FordDivisionId": 114,
        "VehicleName": "Ford Escape",
        "VehicleYear": 2005,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 18,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 82,
        "ModelColorId": 100,
        "ModelImagePrefix": "FES2005",
        "DateCreated": "2008-02-07T22: 22: 33",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 32: 46",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "5-Door Sport Utility",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 10,
        "FordDivisionId": 114,
        "VehicleName": "Ford F-350 Lariat Super Duty",
        "VehicleYear": 2005,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 21,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 101,
        "ModelImagePrefix": "F350L2005",
        "DateCreated": "2008-02-24T01: 49: 10",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T03: 55: 33",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (4-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green/Silver"
    },
    {
        "ModelID": 39,
        "FordDivisionId": 114,
        "VehicleName": "Ford 150 Lariat 5.4 Triton",
        "VehicleYear": 2006,
        "VehicleCategoryId": 4,
        "VehicleBodyStyleId": 21,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 97,
        "ModelImagePrefix": "F150L2006",
        "DateCreated": "2008-03-03T03: 48: 15",
        "CreatedBy": "0",
        "DateModified": "2008-03-03T03: 48: 15",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Truck",
        "VehicleBodyStyleName": "Pickup Truck (4-Door)",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Dark Green"
    },
    {
        "ModelID": 84,
        "FordDivisionId": 114,
        "VehicleName": "Ford Explorer Eddie Bauer",
        "VehicleYear": 2006,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 18,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 108,
        "ModelImagePrefix": "EXP2006",
        "DateCreated": "2008-03-12T05:30:31",
        "CreatedBy": "0",
        "DateModified": "2008-03-12T05:35:15",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "5-Door Sport Utility",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1:18",
        "ModelColorName": "Silver"
    },
    {
        "ModelID": 28,
        "FordDivisionId": 114,
        "VehicleName": "Ford Fusion",
        "VehicleYear": 2006,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 17,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "FFU2006",
        "DateCreated": "2008-02-18T19:03:47",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T19:04:53",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "4-Door Sedan",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1:24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 1,
        "FordDivisionId": 114,
        "VehicleName": "Ford Explorer XLT",
        "VehicleYear": 2015,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 18,
        "VehicleEngineId": 54,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "FEX2015",
        "DateCreated": "2019-03-02T21:29:37",
        "CreatedBy": "0",
        "DateModified": "2019-03-02T21:31:10",
        "ModifiedBy": "0",
        "FordDivisionName": "Ford",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "5-Door Sport Utility",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1:18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 20,
        "FordDivisionId": 115,
        "VehicleName": "Lincoln Zephyr",
        "VehicleYear": 1939,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 49,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "Introduced in November of 1935 as a 1936 model, the Lincoln-Zephyr was extremely modern with a low raked windscreen, integrated fenders, and aerodynamic design. It is noted for being one of the first successful streamlined cars after the Chrysler Airflow. The Lincoln-Zephyr was extremely successful in reigniting sales at Lincoln dealerships in the late 1930s, spawning the Continental line that would replace the aging K-series by the end of the decade. By 1941, Lincoln-Zephyr, Continental, and the Zephyr-based Custom line were the only models offered at Lincoln dealerships.rnrnProduction of all American cars halted in 1942 as the country entered World War II, with Lincoln producing the last Lincoln-Zephyr on January 31. After the war, most makers restarted production of their pre-war lines, and Lincoln was no exception. The Zephyr name, however, was no longer used after 1942, with the cars simply called Lincolns.",
        "ModelManufacturerId": 80,
        "ModelScaleId": 81,
        "ModelColorId": 109,
        "ModelImagePrefix": "LZ1939",
        "DateCreated": "2008-02-08T01: 23: 58",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 28: 49",
        "ModifiedBy": "0",
        "FordDivisionName": "Lincoln",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "I6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 18",
        "ModelColorName": "White"
    },
    {
        "ModelID": 91,
        "FordDivisionId": 115,
        "VehicleName": "Lincoln Capri",
        "VehicleYear": 1952,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 10,
        "VehicleEngineId": 53,
        "VehicleHighlight": "The Capri became a separate line and the top series for 1952 with the Lincoln restyle. Styling was tasteful and subdued, especially in comparison to contemporary Cadillac.�Like most cars of this era, they were fairly heavy, weighing in at a prodigious 4,635 pounds. The 1952 Lincolns were technologically innovative cars, introducing the first ball joint front suspension of any car and Ford first overhead valve V8. The Capri was Lincoln top of the line model. Like the Cosmopolitan it resembled, its gas tank filler was hidden behind the rear license plate.",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "LCP1952",
        "DateCreated": "2011-02-21T05: 49: 42",
        "CreatedBy": "0",
        "DateModified": "2011-05-11T21: 28: 01",
        "ModifiedBy": "0",
        "FordDivisionName": "Lincoln",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 6,
        "FordDivisionId": 115,
        "VehicleName": "Lincoln Navigator",
        "VehicleYear": 1998,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 18,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "LN1998",
        "DateCreated": "2008-02-07T22: 21: 28",
        "CreatedBy": "0",
        "DateModified": "2008-02-18T15: 34: 53",
        "ModifiedBy": "0",
        "FordDivisionName": "Lincoln",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "5-Door Sport Utility",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 15,
        "FordDivisionId": 115,
        "VehicleName": "Navicross Concept",
        "VehicleYear": 2003,
        "VehicleCategoryId": 3,
        "VehicleBodyStyleId": 16,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "The Lincoln Navicross concept vehicle is a breakthrough all-conditions sport sedan that shatters the accepted car, crossover and sport utility vehicle paradigms. Designed to be visually striking, dynamically engaging and uniquely practical, Navicross creates an all new, yet unnamed industry niche. rnrnThe Lincoln Navicross represents the next step in applying the Lincoln design DNA � a process that began with the Lincoln MK9 concept in 2001 and, a year later, the Lincoln Continental show car.rnrnBy developing the design DNA through concepts, Lincoln is transforming its products, first by applying their influence in new Lincoln interior designs. Beginning with new 2002 and 2003 products, Lincoln has tripled its investment in interior design. Elements of the show cars are found in today's world-class interiors of the Lincoln Aviator and Navigator. Navicross demonstrates that the Lincoln vision can be both restrained and dramatic, providing an emotional and compelling outlook on the future of Lincoln's product range, says Gerry McGovern, design director, Lincoln Mercury. We've shown how our interior designs translate into production. Through our concepts, our design DNA will continue to redefine the Lincoln brand inside and out.�",
        "ModelManufacturerId": 68,
        "ModelScaleId": 81,
        "ModelColorId": 104,
        "ModelImagePrefix": "LNC2006",
        "DateCreated": "2008-02-08T01: 09: 10",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T19: 30: 51",
        "ModifiedBy": "0",
        "FordDivisionName": "Lincoln",
        "VehicleCategoryName": "SUV",
        "VehicleBodyStyleName": "4-Door Crossover",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Lincoln"
    },
    {
        "ModelID": 2,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Coupe",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 48,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 82,
        "ModelColorId": 106,
        "ModelImagePrefix": "MC1949",
        "DateCreated": "2008-02-07T17: 20: 28",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T19: 07: 16",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "I4",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 35,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Police Car",
        "VehicleYear": 1949,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 12,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 58,
        "ModelScaleId": 81,
        "ModelColorId": 93,
        "ModelImagePrefix": "MRC1949P",
        "DateCreated": "2008-03-07T05: 59: 59",
        "CreatedBy": "0",
        "DateModified": "2010-12-03T19: 44: 17",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Sedan",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Ertl Collectibles",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black/Yellow"
    },
    {
        "ModelID": 36,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Custom Woodie",
        "VehicleYear": 1950,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 13,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 66,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "MCW1950",
        "DateCreated": "2008-03-07T06: 18: 20",
        "CreatedBy": "0",
        "DateModified": "2010-12-03T19: 45: 30",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Station Wagon",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Mattel",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 92,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Marauder",
        "VehicleYear": 1964,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 54,
        "VehicleHighlight": "The Mercury Marauder was the name of three different automobiles made by the Mercury division of Ford Motor Company.  During the 1960s, the Marauder was introduced as the high-performance model of the full-size Mercury line; its Ford equivalent was the Ford_Galaxie. From 2003, the Marauder nameplate was revived as a high-performance variant of the full-size Grand Marquis. After lower than expected sales, the Marauder was discontinued at the end of the 2004 model year.",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "MAR1964",
        "DateCreated": "2011-02-21T05: 51: 57",
        "CreatedBy": "0",
        "DateModified": "2011-02-21T06: 20: 44",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 93,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Cyclone GT",
        "VehicleYear": 1966,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 54,
        "VehicleHighlight": "The Comet Cyclone was offered from 1964 to 1972. The first intro  hit the market in 1964 with a 289 V8 rated at 210 hp. Mercury dealers also offered a line of Cobra high performance equipment available for the 289 V-8 engine. A special 271 hp version of the 289 V-8 was offered, a Cobra heavy-duty clutch, special carburetors, air cleaners, valve covers and many other performance related items were offered  under this special Cobra line. In 1966 Mercury went full blast and offered a Cyclone GT powered by a 335hp 390 V8 and in 1967 Mercury offered a 427 with 425 hp.",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 78,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "MCGT1966",
        "DateCreated": "2011-02-21T05: 53: 09",
        "CreatedBy": "0",
        "DateModified": "2011-02-21T06: 08: 30",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "Yat Ming",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 47,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Cougar XR7",
        "VehicleYear": 1967,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 10,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 74,
        "ModelScaleId": 81,
        "ModelColorId": 100,
        "ModelImagePrefix": "XR71967",
        "DateCreated": "2008-03-08T05: 29: 50",
        "CreatedBy": "0",
        "DateModified": "2010-12-03T19: 46: 16",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Sun Star",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Green"
    },
    {
        "ModelID": 80,
        "FordDivisionId": 116,
        "VehicleName": "Mercury Cougar Eliminator",
        "VehicleYear": 1970,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 10,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "MCE1970",
        "DateCreated": "2008-03-09T19: 49: 46",
        "CreatedBy": "0",
        "DateModified": "2008-03-09T19: 49: 46",
        "ModifiedBy": "0",
        "FordDivisionName": "Mercury",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 46,
        "FordDivisionId": 117,
        "VehicleName": "Ford Mustang 1964",
        "VehicleYear": 1964,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 10,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 67,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "MST1964B",
        "DateCreated": "2008-03-04T06: 18: 38",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T22: 52: 57",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Hardtop",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "MIRA (Spain)",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 69,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Convertible",
        "VehicleYear": 1964,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 72,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "MCC1964",
        "DateCreated": "2008-03-11T01: 51: 03",
        "CreatedBy": "0",
        "DateModified": "2010-11-30T18: 21: 19",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Solido",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 68,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Fastback",
        "VehicleYear": 1965,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 72,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "FMF1965",
        "DateCreated": "2008-03-11T01: 40: 27",
        "CreatedBy": "0",
        "DateModified": "2010-04-23T22: 37: 48",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Solido",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 24,
        "FordDivisionId": 117,
        "VehicleName": "Mustang GT",
        "VehicleYear": 1967,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 80,
        "ModelScaleId": 82,
        "ModelColorId": 94,
        "ModelImagePrefix": "MGT1967",
        "DateCreated": "2008-02-07T21: 40: 31",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T19: 40: 50",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "Other",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 62,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Boss 302",
        "VehicleYear": 1969,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "MB3021969",
        "DateCreated": "2008-03-09T20: 43: 20",
        "CreatedBy": "0",
        "DateModified": "2010-12-02T23: 10: 35",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 30,
        "FordDivisionId": 117,
        "VehicleName": "Ford Mustang Boss 429",
        "VehicleYear": 1970,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 14,
        "VehicleEngineId": 52,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 82,
        "ModelColorId": 94,
        "ModelImagePrefix": "FMB4291970",
        "DateCreated": "2008-02-19T05: 10: 09",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T22: 52: 03",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "3-Door Hatchback Coupe",
        "VehicleEngineName": "V6",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 81,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Boss 429",
        "VehicleYear": 1970,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 68,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "MB4291970",
        "DateCreated": "2008-03-09T20: 08: 18",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T23: 03: 29",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "MotorMax",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 61,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Sportsroof",
        "VehicleYear": 1971,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 74,
        "ModelScaleId": 81,
        "ModelColorId": 102,
        "ModelImagePrefix": "MSR1971",
        "DateCreated": "2008-03-09T20: 18: 26",
        "CreatedBy": "0",
        "DateModified": "2010-12-02T00: 02: 43",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Sun Star",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Light Braun"
    },
    {
        "ModelID": 25,
        "FordDivisionId": 117,
        "VehicleName": "Ford Mustang Mach1",
        "VehicleYear": 1973,
        "VehicleCategoryId": 2,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 62,
        "ModelScaleId": 82,
        "ModelColorId": 90,
        "ModelImagePrefix": "MACH1973",
        "DateCreated": "2008-02-18T23: 08: 42",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T22: 49: 14",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Sports",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Jada",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black/Gold"
    },
    {
        "ModelID": 65,
        "FordDivisionId": 117,
        "VehicleName": "Mustang Mach 1 Eleanor",
        "VehicleYear": 1973,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 9,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 58,
        "ModelScaleId": 81,
        "ModelColorId": 112,
        "ModelImagePrefix": "MMEL1973",
        "DateCreated": "2008-03-09T21: 51: 08",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T18: 49: 14",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Fastback",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Ertl Collectibles",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Yellow"
    },
    {
        "ModelID": 64,
        "FordDivisionId": 117,
        "VehicleName": "Mustang SVO",
        "VehicleYear": 1986,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 14,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 76,
        "ModelScaleId": 81,
        "ModelColorId": 89,
        "ModelImagePrefix": "FMSVO1986",
        "DateCreated": "2008-03-09T21: 04: 05",
        "CreatedBy": "0",
        "DateModified": "2010-12-03T19: 43: 27",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "3-Door Hatchback Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Welly",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 71,
        "FordDivisionId": 117,
        "VehicleName": "Mustang GT 99",
        "VehicleYear": 1999,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 94,
        "ModelImagePrefix": "MGT1999",
        "DateCreated": "2008-03-11T02: 34: 11",
        "CreatedBy": "0",
        "DateModified": "2010-04-23T22: 10: 14",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Blue"
    },
    {
        "ModelID": 59,
        "FordDivisionId": 117,
        "VehicleName": "Shinoda Boss Mustang",
        "VehicleYear": 1999,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 106,
        "ModelImagePrefix": "ShinodaM",
        "DateCreated": "2008-03-09T17: 13: 29",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T22: 54: 07",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Red"
    },
    {
        "ModelID": 70,
        "FordDivisionId": 117,
        "VehicleName": "Mustang SVT Cobra",
        "VehicleYear": 2003,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 7,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 81,
        "ModelColorId": 108,
        "ModelImagePrefix": "MSVT2003",
        "DateCreated": "2008-03-11T02: 09: 22",
        "CreatedBy": "0",
        "DateModified": "2010-04-23T22: 13: 45",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Convertible",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Silver"
    },
    {
        "ModelID": 77,
        "FordDivisionId": 117,
        "VehicleName": "Ford Mustang GT 2006",
        "VehicleYear": 2006,
        "VehicleCategoryId": 1,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 53,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 64,
        "ModelScaleId": 82,
        "ModelColorId": 89,
        "ModelImagePrefix": "MGT2006",
        "DateCreated": "2008-03-09T18: 44: 41",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T22: 55: 19",
        "ModifiedBy": "0",
        "FordDivisionName": "Mustang",
        "VehicleCategoryName": "Car",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "V8",
        "ModelManufacturerName": "Maisto",
        "ModelScaleName": "1: 24",
        "ModelColorName": "Black"
    },
    {
        "ModelID": 26,
        "FordDivisionId": 119,
        "VehicleName": "Shelby G.T. 350R",
        "VehicleYear": 1965,
        "VehicleCategoryId": 2,
        "VehicleBodyStyleId": 8,
        "VehicleEngineId": 54,
        "VehicleHighlight": "",
        "VehicleHistoryNote": "",
        "ModelManufacturerId": 70,
        "ModelScaleId": 81,
        "ModelColorId": 106,
        "ModelImagePrefix": "SGT350R",
        "DateCreated": "2008-02-18T18: 37: 00",
        "CreatedBy": "0",
        "DateModified": "2010-12-01T19: 34: 32",
        "ModifiedBy": "0",
        "FordDivisionName": "Shelby",
        "VehicleCategoryName": "Sports",
        "VehicleBodyStyleName": "2-Door Coupe",
        "VehicleEngineName": "Other",
        "ModelManufacturerName": "Shelby Collectibles",
        "ModelScaleName": "1: 18",
        "ModelColorName": "Red"
    }
]